<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository {
    
    public function getAdGridList($limit = 0, $offset = 10, $order_by = "id", $sort_order = "asc", $searchData, $SearchType, $objHelper, $user) {
        
        $data = $this->trim_serach_data($searchData, $SearchType);

        
        $query = $this->createQueryBuilder('b');
        
        if ($SearchType == 'ORLIKE') {
            $likeStr = $objHelper->orLikeSearch($data);
        }
        if ($SearchType == 'ANDLIKE') {
            $likeStr = $objHelper->andLikeSearch($data);
        }
        
        if ($likeStr) {
            $query->andWhere($likeStr);
        }

        $countCms = count($query->getQuery()->getArrayResult());
        $query->orderBy($order_by, $sort_order);
        $query->setMaxResults($limit);
        $query->setFirstResult($offset);

        $result = $query->getQuery()->getResult();

        $dataResult = array();

        if (count($result) > 0) {

            $dataResult['result'] = $result;
            $dataResult['totalRecord'] = $countCms;

            return $dataResult;

        }
        return false;
    }

    public function trim_serach_data($searchData, $SearchType) {

        $QueryStr = array();

        if (!empty($searchData)) {

            if ($SearchType == 'ANDLIKE') {

                $i = 0;
                foreach ($searchData as $key => $val) {
                    
                    if ($key == 'Name' && !empty($val)) {
                        
                        $QueryStr[$i]['Field'] = 'b.title';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = 'LIKE';
                    }
                    $i++;
                }
            } else {
                !empty($searchData['Title']) ? $QueryStr['b.title'] = $searchData['Title'] : "";
                //!empty($searchData['Type']) ? $QueryStr['a.type'] = $searchData['Type'] : "";
                //!empty($searchData['Status']) ? $QueryStr['a.status'] = $searchData['Status'] : "";
            }
        }
        return $QueryStr;
    }
    
    
    public function getBlogList($limit = 0, $offset = 10, $order_by = "id", $sort_order = "asc", $searchData, $SearchType, $objHelper, $user) {
        $query = $this->createQueryBuilder('b');
        
        $likeStr = '';
        if ($SearchType == 'ORLIKE') {
            $likeStr = $objHelper->orLikeSearch($data);
        }
        if ($SearchType == 'ANDLIKE') {
            $likeStr = $objHelper->andLikeSearch($data);
        }
        
        if ($likeStr) {
            $query->andWhere($likeStr);
        }

        //$query->orderBy($order_by, $sort_order);
        //$query->setMaxResults($limit);
        //$query->setFirstResult($offset);

        $result = $query->getQuery()->getResult();

        return $result;
    }
}
